package: d2u_videos
version: '1.0'
author: Tobias Krais
supportpage: http://github.com/tobiaskrais/d2u_videos

page:
    title: 'translate:d2u_videos'
    perm: d2u_videos[]
    icon: rex-icon fa-video-camera
    subpages:
        videos: { title: 'translate:d2u_videos_videos', icon: rex-icon fa-video-camera }
        playlist: { title: 'translate:d2u_videos_playlists', icon: rex-icon fa-list-ol, perm: d2u_videos[edit_data] }
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, perm: d2u_videos[settings] }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, perm: d2u_videos[settings] }

requires:
    redaxo: '>=5.2.0'
    php:
        version: '>=7.0'
    packages:
        d2u_helper: '>=1.2.4'